---
title: "shaded_2d_venn()"
author: "Adrià Mitjavila Ventura"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    self_contained: yes
    mode: selfcontained
vignette: >
  %\VignetteIndexEntry{shaded_2d_venn()}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align = "center", fig.width = 4, fig.height = 4, 
                      warning = FALSE, error = FALSE, message = FALSE)
devtools::load_all("..")
```

Last updated: `r Sys.Date()`

***

```{r results=FALSE}
# Load ggplot2
library(ggplot2)

# Load ggmitji 
library(ggmitji)

# Load patchwork (to put plots together)
library(patchwork)
```


```{r results=FALSE}
areas <-
  shaded_2d_venn(highlight = "all", color = "white", line.col = "black") +
  annotate("text", label = "AB", x = .5, y = .5, hjust = .5, vjust = .5) +
  annotate("text", label = "AnoB", x = .2, y = .5, hjust = .5, vjust = .5) +
  annotate("text", label = "noAB", x = .8, y = .5, hjust = .5, vjust = .5) +
  annotate("text", label = "Name of each area", x = .5, y = 1.06, hjust = .5, vjust = 0, fontface = "bold", size = 8) +
  coord_cartesian(ylim = c(0, 1))
```

```{r}
areas
```


```{r results=FALSE}
v1 <- shaded_2d_venn(highlight = "AB", color = "red")
v2 <- shaded_2d_venn(highlight = "noAB", color = "green")
v3 <- shaded_2d_venn(highlight = "AnoB", color = "yellow")
v4 <- shaded_2d_venn(highlight = c("AB", "AnoB", "noAB"), c("red", "yellow", "green"))
v5 <- shaded_2d_venn(highlight = "all", color = "black", line.col = "white")
```


```{r fig.height=4, fig.width=7}
(v1 + v2 + v3) / (v4 + v5)
```



