---
title: "draw_polygon()"
author: "Adrià Mitjavila Ventura"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    self_contained: yes
    mode: selfcontained
vignette: >
  %\VignetteIndexEntry{draw_polygon()}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align = "center", fig.width = 4, fig.height = 4, 
                      warning = FALSE, error = FALSE, message = FALSE)
devtools::load_all("..")
```

Last updated: `r Sys.Date()`

***

```{r results=FALSE}
# Load ggmitji 
library(ggmitji)

# Load patchwork (to put plots together)
library(patchwork)
```

```{r, include=FALSE, results=FALSE}
draw_polygon(shape = "L", color = "Black", fill = "NA")
```

```{r results=FALSE}
l = draw_polygon(shape = "L", color = "Black", fill = NA)
s = draw_polygon(shape = "square", color = "red", fill = "cornflowerblue")
t = draw_polygon(shape = "triangle", color = "Black", fill = "pink")
c = draw_polygon(shape = "circle", color = "Black", fill = "yellow")
```

```{r fig.height=6, fig.width=7}
(l + s + t + c)
```



