# -------------- #
# theme_ggvenn() #
# -------------- #

#' @title theme_custom
#' @author amitjavilaventura
#'
#' @description
#' Custom theme for ggplot2 that allows to customize several things from a plot. Is specially designed for plots generated by `ggvenn::ggvenn()`
#' It uses `ggplot2::theme()`
#'
#' @seealso `ggplot2::theme()`
#' @seealso `ggvenn::ggvenn()`
#'
#' @export

theme_ggvenn <- function(title.hjust = .5,
                         title.face = "plain",
                         subtitle.face = "italic",
                         title.family = "sans",
                         subtitle.family = "sans",
                         caption.face = "plain",
                         caption.hjust = 1,
                         caption.family = "sans"){

  theme(plot.title = element_text(face = title.face, hjust = title.hjust, family = title.family),
        plot.subtitle = element_text(face = subtitle.face, hjust = title.hjust, family = subtitle.family),
        plot.caption = element_text(face = caption.face, hjust = caption.hjust, family = caption.family))
}
